# Generated by Django 4.0.1 on 2023-11-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_crawled_at_alter_news_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
