# Generated by Django 4.0.1 on 2023-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_content_alter_news_crawled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
