# Generated by Django 4.0.1 on 2023-11-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
